name: CI with Tests and Coverage

on: [push, pull_request]

jobs:
  build_and_test:
    name: Build and Test on Linux
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - compiler: gcc
            cpp_compiler: g++
            coverage: true
            build_type: Debug
          - compiler: clang
            cpp_compiler: clang++
            coverage: false

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake clang
        sudo apt-get install -y python3-pip
        sudo pip install gcovr

    - name: Configure CMake
      run: |
        cmake -H. -B build-${{matrix.compiler}} \
          -D CMAKE_CXX_COMPILER=${{matrix.cpp_compiler}} \
          -D CMAKE_C_COMPILER=${{matrix.compiler}} \
          -D CMAKE_BUILD_TYPE=${{matrix.build_type}} \
          -D BUILD_TESTS=ON \
          -D TESTS_NAME=tests \
          -D ENABLE_COVERAGE=${{matrix.coverage}} \
          -D CMAKE_CXX_FLAGS="${{ matrix.coverage && '--coverage -fprofile-abs-path' || '' }}" \
          -D CMAKE_EXE_LINKER_FLAGS="${{ matrix.coverage && '--coverage' || '' }}"

    - name: Build project
      run: |
        cmake --build build-${{matrix.compiler}} -- -j$(nproc)

    - name: Run tests
      run: |
        cd build-${{matrix.compiler}}
        ./tests --gtest_output=xml:test_results.xml

    - name: Generate coverage (for GCC)
      if: matrix.coverage
      run: |
        cd build-${{matrix.compiler}}

        gcovr -r $GITHUB_WORKSPACE \
              -f '.*/banking/.*' \
              --object-directory . \
              --exclude-unreachable-branches \
              --exclude-noncode-lines \
              --exclude-lines-by-pattern 'assert\(.*\);' \
              --print-summary \
              --lcov source_coverage.info

        if [ ! -s source_coverage.info ]; then
          echo "Error: source_coverage.info is empty!"
          ls -l
          exit 1
        fi
        
        echo "Coverage file content:"
        head -n 20 source_coverage.info
        echo "..."

    - name: Upload coverage to Coveralls
      if: matrix.coverage
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: build-${{matrix.compiler}}/source_coverage.info
        parallel: true
        flag-name: gcc-run

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results-${{matrix.compiler}}
        path: build-${{matrix.compiler}}/test_results.xml

    - name: Upload coverage info
      uses: actions/upload-artifact@v4
      with:
        name: coverage-info-${{matrix.compiler}}
        path: build-${{matrix.compiler}}/source_coverage.info

  coveralls_finalize:
    name: Coveralls Finalize
    needs: build_and_test
    runs-on: ubuntu-latest
    steps:
      - name: Finalize Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
