name: CI with Tests and Coverage

on: [push, pull_request]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y lcov build-essential

    - name: Configure CMake
      run: |
        cmake -B build -DBUILD_TESTS=ON -DENABLE_COVERAGE=ON

    - name: Build project
      run: |
        cmake --build build -- -j$(nproc)

    - name: Run Google Tests
      run: |
        cd build/test
        ./tests --gtest_output=xml:test_results.xml

    - name: Generate coverage
      run: |
        cd build
        lcov --capture --directory . --output-file coverage.info
        lcov --remove coverage.info '*/test/*' '*/third-party/*' -o filtered.info
        lcov --extract filtered.info '*/banking/*' -o result.info

    - name: Upload coverage to Coveralls
      uses: coverallsapp/github-action@v2
      with:
        path-to-lcov: build/result.info
