name: CI with Tests and Coverage

on: [push, pull_request]

jobs:
  linux_build_test:
    name: Build and Test on Linux
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - compiler: gcc
            cpp_compiler: g++
            coverage: true
            build_type: Debug
          - compiler: clang
            cpp_compiler: clang++
            coverage: false

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake clang lcov

    - name: Configure CMake
      run: |
        cmake -S . -B build-${{matrix.compiler}} \
          -D CMAKE_CXX_COMPILER=${{matrix.cpp_compiler}} \
          -D CMAKE_C_COMPILER=${{matrix.compiler}} \
          -D CMAKE_BUILD_TYPE=${{matrix.build_type}} \
          -D BUILD_TESTS=ON \
          -D TESTS_NAME=tests \
          -D ENABLE_COVERAGE=${{matrix.coverage}} \
          -D CMAKE_CXX_FLAGS="${{ matrix.coverage && '--coverage -fprofile-abs-path -O0' || '' }}" \
          -D CMAKE_EXE_LINKER_FLAGS="${{ matrix.coverage && '--coverage' || '' }}"

    - name: Build project
      run: |
        cmake --build build-${{matrix.compiler}} -- -j$(nproc)

    - name: Run tests
      run: |
        cd build-${{matrix.compiler}}
        ./tests --gtest_output=xml:test_results.xml

    - name: Generate coverage with lcov
      if: matrix.coverage
      run: |
        cd build-${{matrix.compiler}}
        
        lcov --ignore-errors mismatch --ignore-errors gcov,gcov --capture --directory . -o coverage.info
        
        lcov --extract coverage.info "*/banking/*" -o filtered_coverage.info
        lcov --extract coverage.info "*/src/Transaction.h" -o transaction_header.info
        lcov --add filtered_coverage.info --add transaction_header.info -o combined_coverage.info
        
        lcov --ignore-errors unused --remove combined_coverage.info \
          "*/test/*" \
          "*/third-party/*" \
          "*/googletest/*" \
          "*/gmock/*" \
          -o final_coverage.info
        
        genhtml final_coverage.info --output-directory coverage_report --ignore-errors

    - name: Upload Linux coverage
      if: matrix.coverage
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: build-${{matrix.compiler}}/final_coverage.info
        parallel: true
        flag-name: linux-gcc

    - name: Upload Linux test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results-linux-${{matrix.compiler}}
        path: build-${{matrix.compiler}}/test_results.xml

    - name: Upload Linux coverage report
      if: matrix.coverage
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report-linux-${{matrix.compiler}}
        path: build-${{matrix.compiler}}/coverage_report

  windows_build_test:
    name: Build and Test on Windows
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Configure CMake
      run: |
        cmake -S . -B build_windows `
          -D BUILD_TESTS=ON `
          -D TESTS_NAME=tests `
          -D ENABLE_COVERAGE=true `
          -D gtest_force_shared_crt=ON

    - name: Build project
      run: |
        cmake --build build_windows --config Release

    - name: Install OpenCppCoverage
      run: choco install opencppcoverage -y

    - name: Run tests with coverage
      run: |
        $coverageTool = "C:\Program Files\OpenCppCoverage\OpenCppCoverage.exe"
        $testExe = (Get-ChildItem -Path "build_windows\Release\tests.exe").FullName
        & "$coverageTool" `
          --sources "banking\*.cpp" `
          --sources "src\Transaction.h" `
          --export_type=cobertura:coverage.xml `
          -- "$testExe"

    - name: Install Python dependencies
      run: |
        python -m pip install lcov-cobertura

    - name: Convert to LCOV format
      run: |
        lcov-cobertura coverage.xml -o coverage_windows.info

    - name: Upload Windows coverage
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: coverage_windows.info
        parallel: true
        flag-name: windows-msvc

    - name: Upload Windows test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results-windows
        path: build_windows/Release/test_results.xml

  coveralls_finalize:
    name: Coveralls Finalize
    needs: 
      - linux_build_test
      - windows_build_test
    runs-on: ubuntu-latest
    steps:
      - name: Finalize Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
